name: Vale Prose Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vale:
    name: Lint Prose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Vale Linter
        uses: errata-ai/vale-action@v2
        with:
          files: '.'
          min_alert_level: error
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
